### ISSUE TITLE
libretuya-esphome support for wb2l_m1 board?

### ISSUE THREAD

**Issue by Elkropac** [kuba2k2/libretuya#100]
Hi,
i have some bulbs with wb2l_m1 like this one https://www.elektroda.com/rtvforum/topic3880540.html .
I have succesfully flashed it with openbeken using tuya-cutter.
But I would like to use it with libretuya-esphome.
I tried to place
```
libretuya:
  board: wb2l_m1
  framework:
    version: latest
```
to config, but it does not compile.
Is there a way to compile it?
