### ISSUE TITLE
ESPHome LibreTuya - adding a HLW8012 sensor causes Hard Fault Error

### ISSUE THREAD

**Issue by mihsu81** [kuba2k2/libretuya#42]
Compiling ESPHome LibreTuya with a HLW8012 sensor causes a Hard Fault Error.

The output of ```platformio device monitor``` with _**rtl_hard_fault_decoder**_:
```
platformio device monitor
C:\Users\Bethayn-Dell\.platformio\packages\toolchain-gccarmnoneeabi\bin\arm-none-eabi-addr2line.exe

Please build project in debug configuration to get more details about an exception.
See https://docs.platformio.org/page/projectconf/build_configurations.html


--- Terminal on COM4 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, hexlify, log2file, nocontrol, printable, rtl_hard_fault_decoder, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
ROM:[V0.1]
FLASHRATE:4
BOOT TYPE:0 XTAL:40000000
IMG1 DATA[1128:10002000]
IMG1 ENTRY[8000521:100021ef]
IMG1 ENTER
CHIPID[000000f6]
read_mode idx:3, flash_speed idx:3
calibration_result:[1:25:13][1:19]
calibration_result:[2:25:13][1:19]
calibration_result:[3:0:0][ff:ff]
calibration_ok:[1:25:13]
FLASH CALIB[NEW OK]
OTA2 ADDR[8100000]
OTAx SELE[0]
OTA1 USE
IMG2 DATA[0x80a0870:3868:0x10005000]
IMG2 SIGN[RTKWin(10005008)]
IMG2 ENTRY[0x10005000:0x8042df9]
System_Init1
System_Init2
I [      0.000] main():54: - LibreTuya v0.10.0+sha.8a4392b.dirty on generic-rtl8710bx-4mb-980k, compiled at Nov 18 2022 09:37:58
I [      0.000] main():58: - Reset reason: 0
I [      0.015] open():81: mainTask: Preferences initialized
[I][logger:283]: Log initialized
[C][status_led:014]: Setting up Status LED...
[C][ota:473]: There have been 3 suspected unsuccessful boot attempts.
[D][lt.preferences:104]: Saving 1 preferences to flash...
[V][lt.preferences:115]: sync: key: 233825507, len: 4
[D][lt.preferences:133]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[V][app:030]: Sorting components by setup priority...
[D][binary_sensor:034]: 'Plug EZVIZ Power Button': Sending initial state OFF
[C][switch.gpio:011]: Setting up GPIO Switch 'Plug EZVIZ'...
[D][switch:013]: 'Plug EZVIZ' Turning ON.
[D][switch:037]: 'Plug EZVIZ': Sending state ON
[D][switch:013]: 'Plug EZVIZ' Turning ON.
RTL8195A[HAL]: Hard Fault Error!!!!
RTL8195A[HAL]: R0 = 0x100061c0
RTL8195A[HAL]: R1 = 0x50
RTL8195A[HAL]: R2 = 0xbb8
RTL8195A[HAL]: R3 = 0x55f0
RTL8195A[HAL]: R12 = 0x0
RTL8195A[HAL]: LR = 0x8029ffd
  0x8029ffd in __gnu_cxx::new_allocator<char>::deallocate(char*, unsigned int) at c:/users/bethayn-dell/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include/c++/5.2.1/ext/new_allocator.h:110
      (inlined by) std::allocator_traits<std::allocator<char> >::deallocate(std::allocator<char>&, char*, unsigned int) at c:/users/bethayn-dell/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include/c++/5.2.1/bits/alloc_traits.h:386
      (inlined by) std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy(unsigned int) at c:/users/bethayn-dell/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include/c++/5.2.1/bits/basic_string.h:185
      (inlined by) std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose() at c:/users/bethayn-dell/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include/c++/5.2.1/bits/basic_string.h:180
      (inlined by) std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() at c:/users/bethayn-dell/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include/c++/5.2.1/bits/basic_string.h:544
      (inlined by) esphome::wifi_info::IPAddressWiFiInfo::unique_id[abi:cxx11]() at src/esphome/components/wifi_info/wifi_info_text_sensor.h:20
      (inlined by) esphome::wifi_info::IPAddressWiFiInfo::dump_config() at src/esphome/components/wifi_info/wifi_info_text_sensor.cpp:9
RTL8195A[HAL]: PC = 0x8038a98
  0x8038a98 in LwIPUDP::write(unsigned char) at C:/Users/Bethayn-Dell/.platformio/platforms/libretuya/arduino/libretuya/libraries/NetUtils/lwip/LwIPUdp.cpp:192
RTL8195A[HAL]: PSR = 0x21000000
RTL8195A[HAL]: BFAR = 0xe000ed38
RTL8195A[HAL]: CFSR = 0x10000
RTL8195A[HAL]: HFSR = 0x40000000
RTL8195A[HAL]: DFSR = 0x0
RTL8195A[HAL]: AFSR = 0x0
RTL8195A[HAL]: PriMask 0x0
RTL8195A[HAL]: BasePri 0x0
RTL8195A[HAL]: SVC priority: 0x00
RTL8195A[HAL]: PendSVC priority: 0xf0
RTL8195A[HAL]: Systick priority: 0xf0
```

The output of ```platformio device monitor``` with _**rtl_hard_fault_decoder**_ after removing the **_wifi_info_** sensor:
```
platformio device monitor
C:\Users\Bethayn-Dell\.platformio\packages\toolchain-gccarmnoneeabi\bin\arm-none-eabi-addr2line.exe

Please build project in debug configuration to get more details about an exception.
See https://docs.platformio.org/page/projectconf/build_configurations.html


--- Terminal on COM4 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, hexlify, log2file, nocontrol, printable, rtl_hard_fault_decoder, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
ROM:[V0.1]
FLASHRATE:4
BOOT TYPE:0 XTAL:40000000
IMG1 DATA[1128:10002000]
IMG1 ENTRY[8000521:100021ef]
IMG1 ENTER
CHIPID[000000f6]
read_mode idx:3, flash_speed idx:3
calibration_result:[1:25:13][1:19]
calibration_result:[2:25:13][1:19]
calibration_result:[3:0:0][ff:ff]
calibration_ok:[1:25:13]
FLASH CALIB[NEW OK]
OTA2 ADDR[8100000]
OTAx SELE[0]
OTA1 USE
IMG2 DATA[0x80a0870:3868:0x10005000]
IMG2 SIGN[RTKWin(10005008)]
IMG2 ENTRY[0x10005000:0x8042df9]
System_Init1
System_Init2
I [      0.000] main():54: - LibreTuya v0.10.0+sha.8a4392b.dirty on generic-rtl8710bx-4mb-980k, compiled at Nov 18 2022 09:37:58
I [      0.000] main():58: - Reset reason: 0
I [      0.015] open():81: mainTask: Preferences initialized
[I][logger:283]: Log initialized
[C][status_led:014]: Setting up Status LED...
[C][ota:473]: There have been 7 suspected unsuccessful boot attempts.
[D][lt.preferences:104]: Saving 1 preferences to flash...
[V][lt.preferences:115]: sync: key: 233825507, len: 4
[D][lt.preferences:133]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[V][app:030]: Sorting components by setup priority...
[D][binary_sensor:034]: 'Plug EZVIZ Power Button': Sending initial state OFF
[C][switch.gpio:011]: Setting up GPIO Switch 'Plug EZVIZ'...
[D][switch:013]: 'Plug EZVIZ' Turning ON.
[D][switch:037]: 'Plug EZVIZ': Sending state ON
[D][switch:013]: 'Plug EZVIZ' Turning ON.
RTL8195A[HAL]: Hard Fault Error!!!!
RTL8195A[HAL]: R0 = 0x100061c0
RTL8195A[HAL]: R1 = 0x50
RTL8195A[HAL]: R2 = 0xbb8
RTL8195A[HAL]: R3 = 0x55f0
RTL8195A[HAL]: R12 = 0x0
RTL8195A[HAL]: LR = 0x8029ffd
  0x8029ffd in std::_Vector_base<esphome::switch_::Switch*, std::allocator<esphome::switch_::Switch*> >::_Vector_impl::_Vector_impl() at c:/users/bethayn-dell/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include/c++/5.2.1/bits/stl_vector.h:87
      (inlined by) std::_Vector_base<esphome::switch_::Switch*, std::allocator<esphome::switch_::Switch*> >::_Vector_base() at c:/users/bethayn-dell/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include/c++/5.2.1/bits/stl_vector.h:125
      (inlined by) std::vector<esphome::switch_::Switch*, std::allocator<esphome::switch_::Switch*> >::vector() at c:/users/bethayn-dell/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include/c++/5.2.1/bits/stl_vector.h:257
      (inlined by) esphome::Application::Application() at src/esphome/core/application.h:54
      (inlined by) __static_initialization_and_destruction_0 at src/esphome/core/application.cpp:155
      (inlined by) _GLOBAL__sub_I__ZN7esphome11Application19register_component_EPNS_9ComponentE at src/esphome/core/application.cpp:157
RTL8195A[HAL]: PC = 0x8038a98
  0x8038a98 in WiFiClass::softAP(char const*, char const*, int, bool, int) at C:/Users/Bethayn-Dell/.platformio/platforms/libretuya/arduino/realtek-ambz/libraries/WiFi/WiFiAP.cpp:80
RTL8195A[HAL]: PSR = 0x21000000
RTL8195A[HAL]: BFAR = 0xe000ed38
RTL8195A[HAL]: CFSR = 0x10000
RTL8195A[HAL]: HFSR = 0x40000000
RTL8195A[HAL]: DFSR = 0x0
RTL8195A[HAL]: AFSR = 0x0
RTL8195A[HAL]: PriMask 0x0
RTL8195A[HAL]: BasePri 0x0
RTL8195A[HAL]: SVC priority: 0x00
RTL8195A[HAL]: PendSVC priority: 0xf0
RTL8195A[HAL]: Systick priority: 0xf0
```

The output of ```platformio device monitor``` with _**rtl_hard_fault_decoder**_ after also removing the **_wifi_signal_** sensor:
```
platformio device monitor
C:\Users\Bethayn-Dell\.platformio\packages\toolchain-gccarmnoneeabi\bin\arm-none-eabi-addr2line.exe

Please build project in debug configuration to get more details about an exception.
See https://docs.platformio.org/page/projectconf/build_configurations.html


--- Terminal on COM4 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, hexlify, log2file, nocontrol, printable, rtl_hard_fault_decoder, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
ROM:[V0.1]
FLASHRATE:4
BOOT TYPE:0 XTAL:40000000
IMG1 DATA[1128:10002000]
IMG1 ENTRY[8000521:100021ef]
IMG1 ENTER
CHIPID[000000f6]
read_mode idx:3, flash_speed idx:3
calibration_result:[1:25:13][1:19]
calibration_result:[2:25:13][1:19]
calibration_result:[3:0:0][ff:ff]
calibration_ok:[1:25:13]
FLASH CALIB[NEW OK]
OTA2 ADDR[8100000]
OTAx SELE[0]
OTA1 USE
IMG2 DATA[0x80a0870:3868:0x10005000]
IMG2 SIGN[RTKWin(10005008)]
IMG2 ENTRY[0x10005000:0x8042df9]
System_Init1
System_Init2
I [      0.000] main():54: - LibreTuya v0.10.0+sha.8a4392b.dirty on generic-rtl8710bx-4mb-980k, compiled at Nov 18 2022 09:37:58
I [      0.000] main():58: - Reset reason: 0
I [      0.018] open():81: mainTask: Preferences initialized
[I][logger:283]: Log initialized
[C][status_led:014]: Setting up Status LED...
[C][ota:473]: There have been 6 suspected unsuccessful boot attempts.
[D][lt.preferences:104]: Saving 1 preferences to flash...
[V][lt.preferences:115]: sync: key: 233825507, len: 4
[D][lt.preferences:133]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[V][app:030]: Sorting components by setup priority...
[D][binary_sensor:034]: 'Plug EZVIZ Power Button': Sending initial state OFF
[C][switch.gpio:011]: Setting up GPIO Switch 'Plug EZVIZ'...
[D][switch:013]: 'Plug EZVIZ' Turning ON.
[D][switch:037]: 'Plug EZVIZ': Sending state ON
[D][switch:013]: 'Plug EZVIZ' Turning ON.
RTL8195A[HAL]: Hard Fault Error!!!!
RTL8195A[HAL]: R0 = 0x100061c0
RTL8195A[HAL]: R1 = 0x50
RTL8195A[HAL]: R2 = 0xbb8
RTL8195A[HAL]: R3 = 0x5208
RTL8195A[HAL]: R12 = 0x0
RTL8195A[HAL]: LR = 0x8029ffd
  0x8029ffd in esphome::Component::defer(std::function<void ()>&&) at src/esphome/core/component.cpp:119
RTL8195A[HAL]: PC = 0x8038a98
  0x8038a98 in wifi_indication at C:/Users/Bethayn-Dell/.platformio/platforms/libretuya/arduino/realtek-ambz/libraries/WiFi/WiFiEvents.cpp:89
RTL8195A[HAL]: PSR = 0x21000000
RTL8195A[HAL]: BFAR = 0xe000ed38
RTL8195A[HAL]: CFSR = 0x10000
RTL8195A[HAL]: HFSR = 0x40000000
RTL8195A[HAL]: DFSR = 0x0
RTL8195A[HAL]: AFSR = 0x0
RTL8195A[HAL]: PriMask 0x0
RTL8195A[HAL]: BasePri 0x0
RTL8195A[HAL]: SVC priority: 0x00
RTL8195A[HAL]: PendSVC priority: 0xf0
RTL8195A[HAL]: Systick priority: 0xf0
```

Below is my config file:
```yaml
substitutions:
  devicename: plug_ezviz
  friendly_name: Plug EZVIZ
  device_description: EZVIZ TT1 Smart Plug CS-T31-16B-EU 
  current_res: "0.00221"
  voltage_div: "955"

esphome:
  name: plug-ezviz
  platformio_options:
    monitor_speed: 115200
    monitor_filters: rtl_hard_fault_decoder

socket:
  implementation: lwip_tcp

libretuya:
  board: generic-rtl8710bx-4mb-980k
  framework:
    version: latest
  loglevel: verbose
  lt_config:
    LT_LOGGER: 1
    LT_LOGLEVEL: LT_LEVEL_VERBOSE
    LT_LOGGER_TIMESTAMP: 1
    LT_LOGGER_CALLER: 1
    LT_LOGGER_TASK: 1
    LT_LOGGER_COLOR: 1
    LT_LOG_HEAP: 1
  sdk_silent: true
  gpio_recover: true

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  reboot_timeout: 1h
  encryption:
    key: xxx

ota:
  password: xxx

web_server:
  port: 80
  auth:
    username: xxx
    password: xxx
  include_internal: true

wifi:
  ssid: "SunnyDay"
  password: "xxx"

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: "xxx"

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
    ssid:
      name: ${friendly_name} Connected SSID
    bssid:
      name: ${friendly_name} Connected BSSID
    mac_address:
      name: ${friendly_name} MAC Wifi Address

button:
  - platform: restart
    name: ${friendly_name} Restart

sensor:
  - platform: wifi_signal
    name: ${friendly_name} Wifi Signal
    update_interval: 60s
    id: ${devicename}_wifi_signal
  - platform: hlw8012
    sel_pin:
      number: D8
      inverted: true
    cf_pin: D11
    cf1_pin: D12
    change_mode_every: 8
    update_interval: 10s
    current:
      name: ${friendly_name} Amperage
      icon: mdi:current-ac
      unit_of_measurement: A
    voltage:
      name: ${friendly_name} Voltage
      icon: mdi:flash-circle
      unit_of_measurement: V
    power:
      id: wattage
      name: ${friendly_name} Wattage
      icon: mdi:flash-outline
      unit_of_measurement: W
    energy:
      name: ${friendly_name} Energy
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}

binary_sensor:
  - platform: gpio
    device_class: power
    pin:
      number: D9
      mode: INPUT_PULLUP
      inverted: true
    name: ${friendly_name} Power Button
    id: ${devicename}_button1
    on_press:
      - switch.toggle: ${devicename}_relay
      - light.toggle: ${devicename}_power_led

switch:
  - platform: restart
    name: "${friendly_name} Restart"
    id: ${devicename}_restart
    internal: true
  - platform: gpio
    name: ${friendly_name}
    pin: D0
    id: ${devicename}_relay
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: ${devicename}_power_led
    on_turn_off:
      - light.turn_off: ${devicename}_power_led

status_led:
  pin:
    number: D1
    inverted: false

light:
  - id: ${devicename}_power_led
    platform: binary
    name: ${friendly_name} Power LED
    output: ${devicename}_led2
    internal: true

output:
  - id: ${devicename}_led2
    platform: gpio
    pin: D14
    inverted: false
```
