### ISSUE TITLE
PWM output for BK7231N

### ISSUE THREAD

**Issue by hunhejj** [kuba2k2/libretuya#50]
I have a light bulb with a BK7231N board in it. How can I define PWM outputs in ESPHome for using it for a light component?  More precisely which platform should I use for the output?

```yaml
# ...

light:
  - platform: rgbww
    name: "my_room"
    red: output_component1
    green: output_component2
    blue: output_component3
    cold_white: output_component4
    warm_white: output_component5
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K

output:
  - platform: ???
    id: output_component1
    pin: P6
  #...
```
