### ISSUE TITLE
The text sensor wifi_info/bssid returns Unknown instead of the BSSID

### ISSUE THREAD

**Issue by mihsu81** [kuba2k2/libretuya#57]
Hi @kuba2k2,
The text sensor wifi_info/bssid returns Unknown instead of the BSSID of the AP to which it connects. The board is _**generic-rtl8710bx-4mb-980k**_

```yaml
text_sensor:
  - platform: wifi_info
    bssid:
      name: ${friendly_name} Connected BSSID 
```
```yaml
libretuya:
  board: generic-rtl8710bx-4mb-980k
  framework:
    version: dev
```
![image](https://user-images.githubusercontent.com/40715497/210345249-15e466f5-daa9-475d-9689-e3a948dbd419.png)
