### ISSUE TITLE
"sh: 1: arm-none-eabi-g++: not found" when compiling ESPHome

### ISSUE THREAD

**Issue by donburch888** [kuba2k2/libretuya#79]
My first LibreTuya-ESPHome compile... 

Simple initial configuration for my Arlec PC191HA power points (uses WB2S module) is 
```
esphome:
  name: pc191ha

libretuya:
  board: wb2s
  framework:
    version: dev

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "dagoba"
  password: "gt49lkxyzzy"

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Pc191Ha Fallback Hotspot"
    password: "7j78Uhtsl4Hi"

captive_portal:

# Example configuration entry
web_server:
  port: 80
```
gives
```
pi@raspi4:~ $ python -m esphome compile PC191HA.yaml
INFO Reading configuration PC191HA.yaml...
INFO Generating C++ source...
INFO Compiling app...
*****************************************************************************************************************************
Obsolete PIO Core v6.1.5 is used (previous was 6.1.6)
Please remove multiple PIO Cores from a system:
https://docs.platformio.org/en/latest/core/installation/troubleshooting.html
*****************************************************************************************************************************
Processing pc191ha (board: wb2s; framework: arduino; platform: https://github.com/kuba2k2/libretuya.git)
-----------------------------------------------------------------------------------------------------------------------------
HARDWARE: BK7231T 120MHz, 256KB RAM, 1.03MB Flash
 - framework-arduino-api @ 3.0.0-a4cbfc+sha.3a4cbfc 
 - framework-beken-bdk @ 0.0.0+v2021.06.07.sha.6491b8c 
 - library-flashdb@03500fa @ 3500.0.0-fa+sha.03500fa 
 - library-lwip@2.1.3-bdk @ 2.1.3-bdk+sha.33191e0 
 - library-printf@6.0.0 @ 6.0.0+sha.8b831c1 
 - tool-ltchiptool @ 2.0.2+sha.7559033 
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- ESPAsyncWebServer-esphome @ 3.0.0
|   |-- AsyncTCP-esphome @ 2.0.0
|-- DNSServer @ 1.1.0
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/pc191ha/src/esphome/components/api/api_connection.cpp.o
sh: 1: arm-none-eabi-g++: not found
Compiling .pioenvs/pc191ha/src/esphome/components/api/api_frame_helper.cpp.o
sh: 1: arm-none-eabi-g++: not found
Compiling .pioenvs/pc191ha/src/esphome/components/api/api_pb2.cpp.o
sh: 1: arm-none-eabi-g++: not found
*** [.pioenvs/pc191ha/src/esphome/components/api/api_connection.cpp.o] Error 127
Compiling .pioenvs/pc191ha/src/esphome/components/api/api_pb2_service.cpp.o
*** [.pioenvs/pc191ha/src/esphome/components/api/api_frame_helper.cpp.o] Error 127
*** [.pioenvs/pc191ha/src/esphome/components/api/api_pb2.cpp.o] Error 127
sh: 1: arm-none-eabi-g++: not found
*** [.pioenvs/pc191ha/src/esphome/components/api/api_pb2_service.cpp.o] Error 127
================================================ [FAILED] Took 3.53 seconds ================================================
pi@raspi4:~ $ 
```

Am I missing something obvious here ?
